{% set name = "curryreader" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/curryreader-{{ version }}.tar.gz
  sha256: 2abaf79c7fe12b56578bc83594afc635c517481395ceedfd527f1dc885e38ded

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - certifi >=2020.6.20
    - cycler >=0.10.0
    - kiwisolver >=1.2.0
    - matplotlib-base >=3.3.2
    - numpy >=1.19.2
    - pillow >=8.0.1
    - pip >=21.0.1
    - pyparsing >=2.4.7
    - python-dateutil >=2.8.1
    - setuptools >=50.3.2
    - six >=1.15.0

test:
  imports:
    - curryreader
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/neuroscan/curry-python-reader
  summary: File reader for Compumedics Neuroscan data formats (.cdt, .dat).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dominikwelke
