{% set name = "curryreader" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/curryreader-{{ version }}.tar.gz
  sha256: 945c2f8fa4f9b19e2bb93b547f2d1b9e225631a96ac6a61e45d609c8a68310fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - certifi >=2020.6.20
    - cycler >=0.10.0
    - kiwisolver >=1.2.0
    - matplotlib-base >=3.3.2
    - numpy >=1.19.2
    - pillow >=8.0.1
    - pip >=21.0.1
    - pyparsing >=2.4.7
    - python-dateutil >=2.8.1
    - setuptools >=50.3.2
    - six >=1.15.0

test:
  imports:
    - curryreader
  commands:
    - pip check
    - python -c "import curryreader; ver = curryreader.__version__; assert ver == '{{ version }}', ver"
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/neuroscan/curry-python-reader
  summary: File reader for Compumedics Neuroscan data formats (.cdt, .dat).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dominikwelke
